Dockerfile
Use multi stage build to minimize size and simplify it.
=> Better dockerfile

.drone.yml, Makefile, bootnode.Dockerfile, kusd.Dockerfile
Creates two dockerfiles, one for the bootnode and one for the kusd.
=> Dockerfiles for the kusd and bootnode

kusd/validator/validator.go
=> Disable auto-start of validation after sync

Makefile, faucet.Dockerfile
Make tasks and dockerfile to release the faucet app
=> Release faucet docker image

internal/kusdapi/backend.go
=> Replaced some functions namespace to kusd instead of eth

Makefile, kusd.Dockerfile
Changes on the makefiles to use the new public docker images to host our images
=> Public docker images

cmd/faucet/faucet.go
Some of the faucet interface was showing mUSD instead of kUSD.
=> Renamed mUSD to kUSD for the faucet

.drone.yml, Makefile, build/.gometalinter.json, build/ci.go, consensus/tendermint/reward_test.go, consensus/tendermint/tendermint.go, core/genesis_alloc.go, kusd/backend.go, kusd/validator/election.go, kusd/validator/states.go, kusd/validator/validator.go
Added Test run on feature push
Added fmt and cyclo complexity check
Added a few simple test to monitor CI results
=> Running test packages on build

.drone.yml
Fixes failing build kusd for missing tools
=> replaced docker image for kusd build

internal/assets/genesis.json, release/testnet_console.toml, release/testnet_genesis.json
Replaced the network ID with a new random one to create a new testnet
=> Use a new network ID

kusd/backend.go, kusd/validator/validator.go
Moved a higher level dependency to a lower level dependency on validator
Aiming to be able to mock Validator dependencies
=> bubbled up network contract instantiation

kusd/backend.go, kusd/handler.go, kusd/validator/states.go, kusd/validator/validator.go
Added Validator interface with all methods from validator struct
Added return errors in methods to gracefully handle them
Logic found in handler when receiving messages (validator.Validating) is now in the Validator it self, and an error is raised if not validating (allows to handle the error), please verify this one as is a slight change in program flow (handler.go)
now most methods might return an identifiable error
=> Refactored validator to interface

kusd/handler.go
PR covers the sync issues that we have been facing (does not complete) for the fast and full mode.
In short, there was an update missing - the logic is a bit different compared to Ethereum due to block finality.
Closes #105 
Closes #126 
Tests:
`Fast
> eth.syncing
{
currentBlock: 616683,
highestBlock: 616870,
knownStates: 20,
pulledStates: 20,
startingBlock: 0
}
> eth.syncing
false
Full
> eth.syncing
{
currentBlock: 616117,
highestBlock: 617081,
knownStates: 0,
pulledStates: 0,
startingBlock: 0
}
> eth.syncing
false`
=> Hotfix/sync termination#105#126

kusd/validator/validator.go
Consistent error handling for `validator.makeDeposit` function.
=> Better error handling for the makeDeposit

kusd/validator/states.go, kusd/validator/validator.go
Deleted commented code and TODOs
Moved into Git issues
No code changes
=> cleaned dead code

kusd/validator/validator.go
Removing Account manager dependency from Validator
=> removed unused account manager dependency

faucet.Dockerfile, release/run_faucet.sh
Introduces a runner for the faucet using testnet values.
=> Add testnet runner to the faucet

release/run_faucet.sh
I pushed an invalid faucet runner by mistake.
=> Fixed faucet runner script

log/format.go
Removes keys from log if message is empty
Closes #199
=> removed key pair from log when error message is empty

internal/web3ext/web3ext.go, knode/api.go
=> export validator.isValidating

kcoin.Dockerfile
The docker image is broken because tries to add missing files.
ref: #358
=> Don't add missing files

.drone.yml
Remove build step in drone.
Closes #
https://github.com/kowala-tech/kcoin/issues/391
=> Remove build in drone

Makefile, client/bootnode.Dockerfile, client/faucet.Dockerfile, client/kcoin.Dockerfile
Make tasks to generate the docker images were failing.
=> Docker images were not being generated

.drone.yml
Drone wasn't able to find the Dockerfiles and built assets because their paths have changed. This PR resolves the issue.
=> Fixed drone build paths

Makefile
The task to rename osx file was not updated.
=> Fix cross-compile task

client/stats/stats.go
Related to https://github.com/ethereum/go-ethereum/issues/15867
Closes #398
=> Fixing panic while collecting old stats

client/contracts/consensus/contracts/mgr/ValidatorMgr.sol
A short summary.
https://github.com/kowala-tech/kcoin/issues/420
Closes #
=> [420] Struct TKN moved to other definitions

.drone.yml
Tweak the docker builder step to build:
- `dev` branch to `dev` label
- `master` branch to `latest` label
- tags as they were
- any other unknown case will push to `dev`, keeping `latest` kind of stable.
=> Build docker images in one step

.drone.yml, Makefile
Close #469 
Build CI docker images in parallel in up to 8 at the same time
=> Build CI docker images in parallel

.drone.yml, client/build/ci.go, client/release/bootnode.Dockerfile, client/release/faucet.Dockerfile, client/release/kcoin.Dockerfile, wallet-backend/Dockerfile
I've updated the custom go image with all the tools we use.
=> Use image 1.0.4

e2e/features/validator.feature, e2e/impl/validation.go
This fixes the random nonce errors in the validator e2e tests.
=> Fixes validator nonce error

client/knode/downloader/downloader.go
We have different consensus from Ethereum, so it's possible to get an empty block from peers. Those peers shouldn't be marked as 'bad' or blocked.
Closes #522
=> Stop marking peer as 'bad' if receive empty block from it

client/cmd/kcoin/chaincmd.go
This fixes the genesis file error (hopefully).
=> Release fix: 0.1.14

netstats/package-lock.json, netstats/package.json
reverted falling dependency 
Closes #576
=> reverted incompatible dependency

Makefile, client/build/ci.go, client/cmd/kcoin/main.go, client/cmd/kcoin/misccmd.go, client/cmd/utils/flags.go, client/vendor/github.com/blang/semver/LICENSE, client/vendor/github.com/blang/semver/README.md, client/vendor/github.com/blang/semver/json.go, client/vendor/github.com/blang/semver/package.json, client/vendor/github.com/blang/semver/range.go, client/vendor/github.com/blang/semver/semver.go, client/vendor/github.com/blang/semver/sort.go, client/vendor/github.com/blang/semver/sql.go, client/vendor/vendor.json, client/version/asset.go, client/version/latest.go, client/version/parser.go, client/version/parser_test.go
This PR enable ability to check latest version asset available in version command.
Also temporary the update command displays all available versions..
The hard coded repository URI is going to be replaced on next PR
=> Version asset check

wallet-tools/app/includes/header.tpl, wallet-tools/app/styles/etherwallet-variables.less
Update styles for wallet-tools. Relates to #501
=> update wallet-tool styles

explorer/config.mainnet.json, explorer/config.testnet.json, explorer/public/css/custom.css, explorer/public/css/default.css, explorer/public/css/layout.css, explorer/public/js/main.js, explorer/public/views/home.html, explorer/views/index.ejs
=> update explorer styles

client/contracts/bindings/consensus/consensus.go, client/contracts/bindings/ownership/multisig.go, client/knode/api.go, e2e/cluster/kcoin_node_builder.go, e2e/cluster/node.go, e2e/cluster/node_runner.go, e2e/features/accounts.feature, e2e/features/faucet.feature, e2e/features/minting.feature, e2e/features/node.feature, e2e/features/token.feature, e2e/features/transactions.feature, e2e/features/validator.feature, e2e/features/wallet_backend.feature, e2e/godog.go, e2e/impl/accounts.go, e2e/impl/cluster.go, e2e/impl/context.go, e2e/impl/faucet.go, e2e/impl/minting.go, e2e/impl/tokens.go, e2e/impl/transactions.go, e2e/impl/validation.go, e2e/impl/wallet_backend.go
Adds two tests to cover token minting in the e2e suite.
=> Added e2e coverage for token minting

client/stats/stats.go
Before when using --stats flag made the client to break. 
Closes #
https://github.com/kowala-tech/kcoin/issues/689
=> Fix stats issue that made the client to die.

.drone.yml
Fixes drone.yml to build cdn on dev push/tag.
=> correct mistake in drone.yml

.drone.yml, client/cmd/utils/flags.go
A short summary.
Mandatory:
Closes #
=> fixed binary repository name

client/version/self_update.go
=> Random delay start for selfupdate

client/cmd/bootnode/main.go, e2e/cluster/node.go
Set bootnode v5 as default.
Closes #
https://github.com/kowala-tech/kcoin/issues/738
=> Add bootnode v5 by default.

Makefile
=> Fix not uploading master binaries

client/common/tx/confirmation.go, client/knode/validator/states.go, client/knode/validator/validator.go
=> knode/validator: included timeouts (tx confirmations)
