kowala-tech/kcoin

cmd/kusd/config.go, sample-kowala.toml, stats/config.go, stats/config_test.go
- Stats url is parsed as a template, replacing variables
- Added `Hostname` variable with the hostname of the machine running the binary.
=> Support for templates in the stats URL

kusd.Dockerfile, release/kusd_with_new_account.sh
Added a script in the docker image to start from a genesis (not included in the image) and with a new account.
=> Script to run with genesis and a new account

kusd/validator/states.go, kusd/validator/validator.go, params/protocol_params.go
- The nodes will wait for a transaction on the first round of the first election - sync genesis validators.
Impact:
- In order to start elections, we will always need to post a transaction (ex: faucet).
Closes #78
=> kusd/validator: 1 second block times

faucet.Dockerfile
Faucet needs the ca certificates to fech https urls like twitter.
=> Adds ca-certificates to the faucet image

release/kusd_with_new_account.sh
Commands with quotes sent to the docker image were not working as expected.
=> shell script wasn't sending quotes properly

build/ci.go
It doesn't fail compiling in go 1.10.
=> Add support for go 1.10

.drone.yml
This removes the CI pipeline that creates a GitHub release on tag push. Instead of doing that, we'll manually create releases in GH which will create tags, which will in turn trigger all the appropriate CI tasks, including the Docker image pushes.
=> Removed GitHub release pipeline

.drone.yml
A small CI change to push Slack notifications into the #dev Slack channel when CI completes (successfully or unsuccessfully) on the `master` and `dev` branches, and also on tag pushes. This will not trigger on feature branches, because that would be annoying.
The only reasons to have this is so that everyone knows when new versions are ready for use, and when a new release is made.
The Slack messages look a bit like this (you'll have to imagine the formatting and links):
```
*CI build #641* on branch hotfix/some-branch *successful* in 1m30s
> Last commit message here
v1.0.3 | Commit 4098b3689c8a5fe9ca7c3ea3f9cf138a6c8b3f57 | Build #641
```
Does this seem useful? Any objections or possible improvements?
=> CI Slack notifications

kusd/validator/sync_waiter.go, kusd/validator/sync_waiter_test.go, kusd/validator/validator.go
A function that waits for Block Sync to finish and then calls a provided function
Example:
```
mux := new(event.TypeMux)
defer mux.Stop()
SyncWaiter(
mux,
func() { fmt.Print("synchronization done!) },
func() { fmt.Print("synchronization failed!") },
)
```
=> Feature/sync waiter - Step 1

.gitignore
Git ignore should only have files and folders related to build tools.
Platform specific files should be added on your local global .gitignore
```
#	 
```
=> removed from git ignore non project related files and folders

kusd/validator/states.go
Prints out an error to the logs when the make deposit fails.
=> Log errors when deposit fails

kusd.Dockerfile
Build Docker image with ca-certificates installed to prevent errors on requesting TLS endpoints via http package.
=> Added ca-certs to image

cmd/faucet/faucet.go, internal/kcoinapi/api.go
Unmarshalling errors like this one "faucet offline: validators field missing" are due to this return message: https://github.com/kowala-tech/kcoin/blob/dev/internal/kcoinapi/api.go#L698
New fields in the block header (required fields) must be added to that return msg otherwise the faucet will not work!
Test: 
Genesis Validator:
./kcoin --config /Users/ricardogeraldes/Code/src/github.com/kowala-tech/kcoin/internal/assets/sample-kowala.toml init /Users/ricardogeraldes/Code/src/github.com/kowala-tech/kcoin/release/testnet_genesis.json
cp /Users/ricardogeraldes/Code/src/github.com/kowala-tech/kcoin/internal/assets/UTC--2018-01-16T16-31-38.006625000Z--d6e579085c82329c89fca7a9f012be59028ed53f /Users/ricardogeraldes/Code/src/github.com/kowala-tech/kcoin/build/bin/.kowala/keystore 
./kcoin …
=> [hotfix] cmd/faucet: unmarshalling errors: validators field missing

Makefile, cluster/docker_images.go, cluster/utils.go, tests/godogs_test.go
Godogs runs from the root, where a very generic `interfaces.go` lives. If e2e at some point load some utility packages like `kcoinclient`, it creates a circular dependency.
This change makes godog run from `/tests` instead of the root.
=> Fixes import circles running godog tests

README.md
This removes outdated links and allows the public repo to be shared.
Closes #381
=> Removed old testnet and Gitter links

cmd/kcoin/main.go, cmd/kcoin/usage.go, cmd/utils/flags.go
This removed the`--v5disc` flag because it's no longer useful. All discovery is V5 now.
Mandatory:
Closes #373
=> Default V5 discovery

release/kcoin.sh
In the e2e tests we need to use generated genesis files and not the default ones. This PR adds a param for the docker runner to specify a genesis file for the init. That genesis file is mounted as a volume when we run the tests.
=> Accept a `--genesis-path` arg into the runner to load a specific genesis

release/kcoin.sh
There's a hardcoded IPC reference for the web control panel that's used in the Docker contain execution. It was throwing an error because the .ipc file has been moved. 
This hardcoded reference is acceptable (for now) because there's a Dockerfile for kUSD (as opposed to kCoin).
=> Updated hardcoded ipc reference

.dockerignore, notifications/api.Dockerfile, notifications/emailer.Dockerfile, notifications/transactions_db_synchronize.Dockerfile, notifications/transactions_publisher.Dockerfile
Build was failing because vendor wasn't fetched. This makes the dockerfile fetch all vendor source.
=> fetch vendor in the dockerfile

Makefile
For some reason the bootnode and the faucet need the bindings too.
=> Require bindings for the bootnode and the faucet

Makefile
The cross-compilation also needs the buildings generated
=> Generate bindings for the cross compile process

notifications/api.Dockerfile, notifications/emailer.Dockerfile, notifications/transactions_db_synchronize.Dockerfile, notifications/transactions_publisher.Dockerfile
Notifications dockerfiles now use our custom go docker image to build the binary and alpine 3.7 for the release image.
=> Refactor notifications dockerfiles

Makefile
For a cleaner S3 folder structure, puts commit and tag releases in folders.
The stable and unstable releases don't change, so all links pointing to them will still work.
=> Put commit and tag binary releases in folders

.drone.yml
This uploads e2e logs as a .zip file, and includes the public URL to the file in the slack notification. The slack notification has also been fixed (it was missing a secret).
=> Improved e2e log access

client/internal/web3ext/web3ext.go, client/knode/api.go, client/knode/backend.go
This improves the console tools to mint.
Minting: `mtoken.mint(from, to, 10)`
Confirming: `mtoken.confirm(from, id)`
the minting returns the transaction ID sent to the contract to perform a minting. The transaction receipts will include logs with the minting ID, necessary for the confirmation.
The following function will help finding out the minting ID:
```
checkTransactionID = function(transaction) {
var receipt = eth.getTransactionReceipt(transaction);
if (receipt.status != "0x1") {
console.error("The transaction is not in the blockchain");
return -1;
}
for (var i = 0; i < receipt.logs.length; i++) {
var log = receipt.logs[i];
if (log.topics[0] == "0x4a504a94899432a9846e1aa406dceb1bcfd538bb839071d49d1e5e23f5be30ef") {
return parseInt(log.topics[2]);
}    
}
console.error("The operation …
```
=> Console minting tools

Makefile
The makefile had the wrong path for the windows binary, which was causing an error.
=> Fix windows binary build

client/p2p/discv5/udp.go, e2e/cluster/kcoin_node_builder.go
A short summary.
Mandatory:
Closes #
=> use bootnodesv5 flag and shorter discoveryV5 packet prefix

client/knode/validator/validator.go
Only return error stop validator is running
=> Warn on stopping a non running validator

Makefile, client/cmd/kcoin/chaincmd.go, client/cmd/utils/flags.go, client/params/bootnodes.go, client/params/config.go, client/params/config_test.go, client/release/kcoin.sh
Modified the  `--dev` flag to act a bit like `--testnet`. It uses the testnet genesis but network ID 1. This will be used for the internal devnet that's in progress. 
The testnet chain ID means that it works exactly like the existing testnet (only we can break it without annoying anyone) and the main network ID means that we can test the p2p against all the Ethereum traffic &mdash; a reasonable simulation of the main net environment.
For anyone who's confused, the networks look like this:
|  Name  |    Netstats URL    | Genesis | Chain ID | Network ID |
|--------|--------------------|---------|----------|------------|
| Main   | kusd.kowala.tech   | Main    |        1 |          1 |
| Zygote | zygote.kowala.tech | Testnet |        2 |          2 |
| Dev    | devnet.kowala.io   | Testnet | …
=> Retool --dev mode for internal devnet

docs/docs/advanced/minting-tokens.md, docs/docs/advanced/official-networks.md, docs/docs/getting-started/download.md, docs/docs/getting-started/testnet.md, docs/mkdocs.yml
We had a bunch of documentation in PRs and issues. I've moved it to the docs directory, so it can appear on the docs website.
=> Moved docs from PRs to proper location

Makefile
This is to prevent locally-compiled binaries on non-OS X machines from being reused in the docker process.
=> Re-added install_tools to docker_go_generate
